# Generated by Django 5.1.4 on 2024-12-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('fruit', 'Meyve'), ('vegetable', 'Sebze'), ('cleaning', 'Temizlik'), ('others', 'Diğer')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_type', models.CharField(choices=[('piece', 'Adet'), ('kg', 'Kilogram')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anasayfa.receipts')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anasayfa.products')),
            ],
        ),
    ]
