# Generated by Django 5.1.4 on 2024-12-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0002_products_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(blank=True, choices=[('fruit', 'Meyve'), ('vegetable', 'Sebze'), ('cleaning', 'Temizlik'), ('others', 'Diğer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('piece', 'Adet'), ('kg', 'Kilogram')], max_length=10, null=True),
        ),
    ]
